name: nbr
description: Generic implementation of the network-bound-resource algorithm in Dart
version: 0.0.3
publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
